name: Build and Analyze (C project with SonarCloud)

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout source
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2️⃣ Install dependencies
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential cmake

      # 3️⃣ Compile project and generate compile_commands.json
      - name: Build C project
        run: |
          mkdir -p build
          cd build
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
          make -j

      # 4️⃣ Run SonarCloud analysis
      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          args: >
            -Dsonar.projectKey=antonioborrelli11-coder_cmedio
            -Dsonar.organization=antonioborrelli11-coder
            -Dsonar.cfamily.compile-commands=build/compile_commands.json
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
